config/routes.rb
Rails.application.routes.draw do
  get 'games/index'

  root 'games#index'

  get 'games/create' => 'games#create'
  get 'games/join_game' => 'games#join_game'
  post 'games/start_game' => 'games#start_game'
  get 'games/password' => 'games#password'
  post 'games/choose_seat' => 'games#choose_seat'
  get 'games/play' => 'games#play'
  get 'games/waiting_to_start' => 'games#waiting_to_start'
  get 'games/choose_team_member' => 'games#choose_team_member'
  post 'games/team_info' => 'games#team_info'
  get 'games/voting' => 'games#voting'
  post 'games/collect_votes' => 'games#collect_votes'
  get 'games/tasking' => 'games#tasking'
  get 'games/waiting' => 'games#waiting'
  get 'games/spy_win' => 'games#spy_win'
  get 'games/resistant_win' => 'games#resistant_win'
  post '/games/collect_tasks' => 'games#collect_tasks'
  post '/games/restart' => 'games#restart'
  get '/games/show_task_result' => 'games#show_task_result'
  get '/games/show_vote_result' => 'games#show_vote_result'

end

app/models/game.rb
class Game < ActiveRecord::Base
    @table = [[2,3,2,3,3],
              [2,3,4,3,4],
              [2,3,3,4,4],
              [3,4,4,5,5],
              [3,4,4,5,5],
              [3,4,4,5,5],
             ]
    
    after_initialize :default_values
    def default_values
        self.game_process ||= 'undefined,undefined,undefined,undefined,undefined'
        self.game_status ||= 'waiting'
    end
    
    def self.full(gid)
        @player_ids = Player.where(game_id: gid).ids
        @seats = []
        @player_ids.each do |player|
            @player = Player.find(player)
            @seats.push(@player.seat_num)
        end
        @game = Game.find(gid)
        (1..@game.player_num).each do |x|
            if not @seats.include?(x)
                return false
            end
        end
        return true
    end
    
    def self.game_process(game_id)
        @game = Game.find(game_id)
        return (@game.game_process).split(',')
    end
    
    def self.spy_number(player_number)
        l = [1,1,1,2,2,3,3,3,4]
        return l[player_number-2]
    end
    
    def self.team_size(gid)
        @game = Game.find(gid)
        if @game.player_num < 5
            return 1
        else
            return @table[@game.player_num-5][Game.round_num(gid)]
        end
    end
    
    def self.round_num(gid)
        @game = Game.find(gid)
        pro = @game.game_process.split(',')
        return pro.index('undefined')
    end
    
    def self.set_sheriff(game_id, sheriff_id)
        @game = Game.find(game_id)
        @game.sheriff_player_id = sheriff_id
        @game.save
    end
    
    def self.move_sheriff(gid)
        @game = Game.find(gid)
        @sheriff = Player.find(@game.sheriff_player_id)
        @seat = @sheriff.seat_num % @game.player_num + 1
        @game.sheriff_player_id = Player.where(game_id: gid, seat_num: @seat).ids[0]
        @game.save
    end
    
    def self.update_game_process(gid)
        @game = Game.find(gid)
        pro = @game.game_process.split(',')
        index = pro.index('undefined')
        min_fail = (@game.player_num>=7 and Game.round_num(gid)==3)? 2:1
        if Player.where(game_id: gid, vote: 'not_pass', in_team: 1).count >= min_fail
            pro[index] = 'fail'
        else
            pro[index] = 'success'
        end
        @game.game_process = pro.join(',')
        @game.game_status = 'task_finish'
        @game.save
    end
    
    def self.is_finish(gid)
        @game = Game.find(gid)
        pro = @game.game_process.split(',')
        return pro.count('fail') == 3 || pro.count('success') == 3
    end
    
    def self.who_wins(gid)
        @game = Game.find(gid)
        pro = @game.game_process.split(',')
        if pro.count('fail') == 3
            return 'spy'
        elsif pro.count('success') == 3
            return 'resistant'
        else
            return nil
        end
    end
    
    def self.restart(gid)
        @game = Game.find(gid)
        @game.game_process = 'undefined,undefined,undefined,undefined,undefined'
        @game.game_status = 'waiting'
        @player_ids = Player.where(game_id: gid).ids
        @player_ids.each do |id|
            @player = Player.find(id)
            @player.role = nil
            @player.save
        end
        @game.save
    end
    
    def self.selected_seats(gid)
        seats = []
        @player_ids = Player.where(game_id: gid).ids
        @player_ids.each do |id|
            @player = Player.find(id)
            seats << @player.seat_num
        end
        
        return seats
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def game_params
    params.require(:game).permit(:player_num, :password)
  end
  
  def index
    session[:game_id] = nil
  end
  
  def create

  end
  
  def join_game
    @games = Game.all
  end
  
  def start_game
    if session[:game_id] == nil
      @game = Game.create!(game_params)
      session[:game_id] = @game.id
      session[:password] = @game.password
      @player = Player.create!({:game_id => @game.id})
      session[:player_id] = @player.id
    else
      if params[:game][:password] == Game.find(session[:game_id]).password
        @game = Game.find(session[:game_id])
        session[:password] = @game.password
        @player = Player.create!({:game_id => @game.id})
        session[:player_id] = @player.id
      else
        flash[:notice] = "Wrong Password!"
        redirect_to '/games/join_game'
        return 
      end
    end
    
    redirect_to '/games/waiting_to_start'
  end
  
  def waiting_to_start
    if session[:game_id] == nil || session[:password] == nil
      redirect_to '/games/index'
      return 
    end
    
    if session[:password] != (Game.find(session[:game_id])).password
      redirect_to '/games/join_game'
    end
    @game = Game.find(session[:game_id])
    @selected = Game.selected_seats(@game.id)
    
    if @game.game_status == 'play'
      redirect_to '/games/play'
    end
  end
  
  def password
    session[:game_id] = params[:id]
  end
  
  def choose_seat
    @player_ids = Player.where(game_id: session[:game_id]).ids
    seats = []
    @player_ids.each do |player|
        @player = Player.find(player)
        seats.push(@player.seat_num)
    end
    if not seats.include?(params[:commit].to_i)
      @player = Player.find(session[:player_id])
      @player.seat_num = params[:commit].to_i
      @player.save
    end
    
    @game = Game.find(session[:game_id])
    if Game.full(@game.id)
      @game.game_status = 'play'
      @game.save
      Pusher.trigger("channel_" + (@game.id).to_s, 'refresh', {})
      redirect_to '/games/play'
    else
      redirect_to '/games/waiting_to_start'
    end
  end
  
  def play
    @game = Game.find(session[:game_id])
    if @game.game_status == 'voting'
      redirect_to '/games/voting'
      return 
    end
    @player_ids = Player.where(game_id: @game.id).ids
    @myself = Player.find(session[:player_id])
    if @myself.role == nil
      spy_number = Game.spy_number(@game.player_num)
      @player_ids.shuffle!
      (@player_ids.first(spy_number)).each do |player_id|
        @player = Player.find(player_id)
        @player.role = "spy"
        @player.save
      end
      (@player_ids.last(@player_ids.length-spy_number)).each do |player_id|
        @player = Player.find(player_id)
        @player.role = "resistant"
        @player.save
      end
      @player_ids.shuffle!
      Game.set_sheriff(session[:game_id], @player_ids.first)
    end
    @game = Game.find(session[:game_id])
    @myself = Player.find(session[:player_id])
    @game_process = Game.game_process(session[:game_id])
    @spy_ids = Player.where(game_id: session[:game_id], role: 'spy').ids
    @teammates = []
    @spy_ids.each do |id|
      if id != session[:player_id]
        @teammates.push(Player.find(id).seat_num)
      end
    end
  end
    
  def choose_team_member
    @game = Game.find(session[:game_id])
    @team_size = Game.team_size(@game.id)
    Player.clear_votes(session[:game_id])
    Player.clear_team(session[:game_id])
  end
  
  def team_info
    @team = params[:team].select{|k,v| v=='1'}.keys
    Player.set_team(session[:game_id], @team)
    @game = Game.find(session[:game_id])
    @game.game_status = 'voting'
    @game.save
    Pusher.trigger("channel_" + (@game.id).to_s, 'refresh', {})
    redirect_to '/games/voting'
  end
  
  def voting
    @game = Game.find(session[:game_id])
    @player = Player.find(session[:player_id])
    @team = []
    @player_ids = Player.where(game_id: @game.id, in_team: 1).ids
    @player_ids.each do |id|
      @team.push(Player.find(id).seat_num)
    end
    @team.sort!
    if @game.game_status != 'voting'
      redirect_to '/games/show_vote_result'
    end
  end
  
  def show_vote_result
    @game = Game.find(session[:game_id])
    @result = Player.show_vote_result(@game.id)
    @pass_or_not = Player.vote_result(@game.id)
    if @pass_or_not
      @game.game_status = 'tasking'
      @game.save
      @next = '/games/tasking'
    else
      @game.game_status = 'play'
      @game.save
      @next = '/games/play'
    end
  end
  
  def collect_votes
    @player = Player.find(session[:player_id])
    if params[:commit] == 'Accept'
      @player.vote = 'pass'
      @player.save
    else
      @player.vote = 'not_pass'
      @player.save
    end
    @game = Game.find(session[:game_id])
    if Player.all_voted(session[:game_id])
      Game.move_sheriff(session[:game_id])
      @game.game_status = "vote_finish"
      @game.save
      Pusher.trigger("channel_" + (@game.id).to_s, 'refresh', {})
      redirect_to '/games/show_vote_result'
    else
      redirect_to '/games/voting'
    end
  end
  
  def tasking
    @player = Player.find(session[:player_id])
    if @player.in_team == 0
      redirect_to '/games/waiting'
    else 
      @game = Game.find(session[:game_id])
      if @game.game_status != 'tasking'
        redirect_to '/games/show_task_result'
      end
    end
  end
  
  def waiting
    @game = Game.find(session[:game_id])
    if @game.game_status != 'tasking'
      redirect_to '/games/show_task_result'
    end
  end
  
  def collect_tasks
    @player = Player.find(session[:player_id])
    if params[:commit] == 'Success'
      @player.vote = 'pass'
      @player.save
    else
      @player.vote = 'not_pass'
      @player.save
    end
    @game = Game.find(session[:game_id])
    if Player.all_done(@game.id)
      Game.update_game_process(@game.id)
      Pusher.trigger("channel_" + (@game.id).to_s, 'refresh', {})
      redirect_to '/games/show_task_result'
    else
      redirect_to '/games/tasking'
    end
  end
  
  def show_task_result
    @result = Player.show_task_result(session[:game_id])
    @game = Game.find(session[:game_id])
    pro = @game.game_process.split(',')
    pro.each do |p|
      if p == 'undefined'
        break
      end
      @success_or_not = p
    end
    if Game.is_finish(@game.id)
      @game.game_status = 'finish'
      @game.save
      if Game.who_wins(@game.id) == 'spy'
        @next = '/games/spy_win'
      elsif Game.who_wins(@game.id) == 'resistant'
        @next = '/games/resistant_win'
      end
    else
      @game.game_status = 'play'
      @game.save
      @next = '/games/play'
    end

  end
  
  def resistant_win
    if session[:game_id] == nil
      redirect_to 'games/index'
    end
  end
  
  def spy_win
    if session[:game_id] == nil
      redirect_to 'games/index'
    end
  end
  
  def restart
    @game = Game.find(session[:game_id])
    if @game.game_status == 'finish'
      Game.restart(session[:game_id])
    end
    redirect_to '/games/play'
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/choose_team_member.html.erb
<h1>Choose team member</h1>

<div class="text-muted">
    <% if @team_size == 1%>
        You should choose <%= "#{@team_size}" %> player
    <% else %>
        You should choose <%= "#{@team_size}" %> players
    <% end %>
</div>


<%= form_for :team, class: "form-horizontal" ,url: '/games/team_info', method: 'post' do |f| %>
    <div class="center jumbotron">
        <% (1..@game.player_num).each do |x| %>
            <%= f.label :seat, "#{x}", class: "control-label" %>
            <%= f.check_box x %>
        <% end %>
    </div>
    <div class="center">
        <%= f.submit "Start Voting", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/games/create.html.erb
<h1>Create a New Game</h1>
<%= form_for :game, class: "form-horizontal", url: '/games/start_game' do |f| %>
    <%= f.label :player_num, 'Player Number', class: "control-label" %>
    <div class="styled-select">
        <%= f.select :player_num, [2,3,4,5,6,7,8,9,10], prompt: "Select player number" %>
    </div>
    
    <%= f.label :password, 'Password', class: "control-label" %>
    <div class="controls">
        <%= f.password_field :password, class: "form-control" %>
    </div>
    
    <div class="controls">
        <%= f.submit 'Create', class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/games/index.html.erb
<div class="center jumbotron">
  <%= link_to "New Game", '/games/create', class: "btn btn-lg btn-primary btn-block" %>
  <%= link_to "Join Game", '/games/join_game', class: "btn btn-lg btn-primary btn-block" %>
</div>

app/views/games/join_game.html.erb
<h1>Game List</h1>

<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<table class="table table-striped">
    <tr>
        <th>Game</th>
        <th>Players</th>
        <th colspan="1"></th>
    </tr>

    <% @games.each do |game| %>
        <tr>
            <td><%= game.id %></td>
            <td><%= game.player_num %></td>
            <td><%= link_to 'Join', games_password_path({:id => game.id}) %></td>
        </tr>
    <% end %>
</table>

app/views/games/password.html.erb
<div class="center">
    <%= form_for :game, url: '/games/start_game', method: "post" do |f| %>
        <%= f.label :password, 'Password', class: "control-label" %>
        <%= f.password_field :password %>
        
        <div class="controls">
            <%= f.submit 'Confirm', class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/games/play.html.erb
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
var pusher = new Pusher('9624582dd73c35f24351', {
  encrypted: true
});

var channel = pusher.subscribe('<%= "channel_#{@game.id}" %>');
channel.bind('refresh', function(data) {
  location.reload();
});

var hide_or_show = 'Hide';
function change_role_info(){
    $('#teammates_info').attr('class', '');
    if(hide_or_show == 'Show'){
       hide_or_show = 'Hide'; 
       $('#teammates_info').slideUp();
       $('#role_info').text("<%= "Player #{@myself.seat_num}"%>");
       $('#role_info_text').attr('class', "text-info");
    } 
    else{
        hide_or_show = 'Show';    
        $('#teammates_info').slideDown();
        if("<%= "#{@myself.role.upcase}"%>" == "SPY"){
            $('#role_info_text').attr('class', "text-danger");
        }
        else{
            $('#role_info_text').attr('class', "text-info");
        }
        $('#role_info').text("<%= "#{@myself.role.upcase}"%>");
    } 
}
</script>
<h1>
    <div id="role_info_text", class="text-info">
        <button type="button" class="plain-button", id="role_info", onclick="change_role_info()">
            <%= "Player #{@myself.seat_num}"%>
        </button>
    </div>
</h1>

<h3>
    <% if @myself.id == @game.sheriff_player_id %>
        <div class="text-info center">
            <p>You are Sheriff</p>
        </div>
    <% end %>
</h3>

<div id="teammates_info" class="hidden">
    <% if @myself.role == 'spy' %>
        <div class="text-danger">
            Teammates:
            <% @teammates.each do |seat|%>
                <%= " #{seat}" %>
            <% end %>
        </div>
    <% end %>
</div>

<div class="center jumbotron">
    <div class="text-left">
        <p>Game Process</p>
    </div>
    
    <table class="table table-striped text-left">
        <tr>
            <th>Task 1</th>
            <th>Task 2</th>
            <th>Task 3</th>
            <th>Task 4</th>
            <th>Task 5</th>
        </tr>
    
        <tr>
            <% @game_process.each do |x| %>
                <% if x == 'success' %>
                    <td>
                        <div class="text-success">
                            <%= "#{x.upcase}"%>
                        </div>
                    </td>
                <% elsif x == 'fail' %>
                    <td>
                        <div class="text-danger">
                            <%= "#{x.upcase}"%>
                        </div>
                    </td>
                <% else %>
                    <td></td>
                <% end %>
            <% end %>
        </tr>
    </table>
</div>

<div class="center">
    <% if @myself.id == @game.sheriff_player_id %>
        <%= button_to 'Start Speaking', '/games/choose_team_member', method: :get, class: 'btn btn-lg btn-primary' %>
    <% end %>
</div>

app/views/games/resistant_win.html.erb
<h1>
    <div class="text-success">
        Resistants win
    </div>
</h1>


<%= form_for :restart, url: '/games/restart', method: 'post' do |f| %>
    <div class="center">
        <%= f.submit "Restart Game", class: "btn btn-lg btn-primary"%>
    </div>
<% end %>

app/views/games/show_task_result.html.erb
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
    var pusher = new Pusher('9624582dd73c35f24351', {
      encrypted: true
    });
    
    var channel = pusher.subscribe('<%= "channel_#{@game.id}" %>');
    channel.bind('refresh', function(data) {
      location.reload();
    });
</script>
<h1>Task Result</h1>

<div class="jumbotron">
    <% if @success_or_not == 'success' %>
        <p>Task Success</p>
    <% else %>
        <p>Task Fail</p>
    <% end %>
    
    <table class="table table-striped">
        <tr>
            <th>Success</th>
            <th>Fail</th>
        </tr>
    
        <tr>
            <td><%= @result[:pass] %></td>
            <td><%= @result[:not_pass] %></td>
        </tr>
    </table>
</div>

<div class="center">
    <%= button_to 'OK', @next, method: :get, class: 'btn btn-lg btn-primary' %>
</div>

app/views/games/show_vote_result.html.erb
<h1>Vote Result</h1>
<div class="jumbotron">
    <% if @pass_or_not %>
        <p>Vote Pass</p>
    <% else %>
        <p>Vote Rejected</p>
    <% end %>
    
    <table class="table table-striped">
        <tr>
            <th>Accept</th>
            <th>Reject</th>
        </tr>
    
        <tr>
            <td><%= @result[:pass] %></td>
            <td><%= @result[:not_pass] %></td>
        </tr>
    </table>
</div>

<div class="center">
    <%= button_to 'OK', @next, method: :get, class: 'btn btn-lg btn-primary' %>
</div>

app/views/games/spy_win.html.erb
<h1>
    <div class="text-danger">
        Spy wins
    </div>
</h1>

<%= form_for :restart, url: '/games/restart', method: 'post' do |f| %>
    <div class="center">
        <%= f.submit "Restart Game", class: "btn btn-lg btn-primary"%>
    </div>
<% end %>

app/views/games/tasking.html.erb
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
  var pusher = new Pusher('9624582dd73c35f24351', {
    encrypted: true
  });

  var channel = pusher.subscribe('<%= "channel_#{@game.id}" %>');
  channel.bind('refresh', function(data) {
    location.reload();
  });
</script>


<h1>On Task</h1>
<div class="center jumbotron">
    <%= form_for :task, url: '/games/collect_tasks', method: 'post' do |f| %>
        <%= f.submit "Success", class: 'btn btn-lg btn-primary' %>
        <%= f.submit "Fail", class: 'btn btn-lg btn-primary'%>
    <% end %>
</div>

app/views/games/voting.html.erb
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
  var pusher = new Pusher('9624582dd73c35f24351', {
    encrypted: true
  });

  var channel = pusher.subscribe('<%= "channel_#{@game.id}" %>');
  channel.bind('refresh', function(data) {
    location.reload();
  });
</script>
<h1>Vote</h1>
<div class="center jumbotron">
    <%= form_for :vote, url: '/games/collect_votes', method: 'post' do |f| %>
        <%= f.submit "Accept", class: 'btn btn-lg btn-primary' %>
        <%= f.submit "Reject", class: 'btn btn-lg btn-primary' %>
    <% end %>
</div>

app/views/games/waiting.html.erb
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
  var pusher = new Pusher('9624582dd73c35f24351', {
    encrypted: true
  });

  var channel = pusher.subscribe('<%= "channel_#{@game.id}" %>');
  channel.bind('refresh', function(data) {
    location.reload();
  });
</script>

<h1>Waiting...</h1>

app/views/games/waiting_to_start.html.erb
<head>
  <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
  <script>
    var pusher = new Pusher('9624582dd73c35f24351', {
      encrypted: true
    });

    var channel = pusher.subscribe('<%= "channel_#{@game.id}" %>');
    channel.bind('refresh', function(data) {
      location.reload();
    });
  </script>
</head>
<body>
    <h1><%= "Game #{@game.id}" %></h1>
    <div class="center jumbotron">
        <%= form_for :seat, url: games_choose_seat_path, method: "post" do |f| %>
            <% (1..@game.player_num).each do |i| %>
                <% if @selected.include?i %>
                    <%= f.submit "#{i}", class: "btn btn-lg btn-primary", disabled: "disabled" %>
                <% else %>
                    <%= f.submit "#{i}", class: "btn btn-lg btn-primary" %>
                <% end %>
            <% end %>
        <% end %>
    </div>
</body>